
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run info
        run: run info

  build-windows:
    runs-on: Windows 11
     steps:
      -uses: git/check@v4
      -name: run info
       run: run info


  build-macos:
    runs-on: macos-latest
      steps:
       -uses: git/check@v4
       -name: run info
        run: run info
